### PR TITLE
Naive fix for ID that treats it as a String

### PR DESCRIPTION
**Pull request by ulrikstrid**
If you want me to change less stuff I can create a new PR

### CODE REVIEW

**Comment by ulrikstrid** [comment]
Might not be *as* naive as I thought. From [graphql.org](http://graphql.org/learn/schema/)

> ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable.

**Comment by wokalski** [comment]
Additionally we added support for custom scalars (they are just `Js.Json.t` for now) and first class support for `Booleans`.

**Comment by wokalski** [comment]
Fixes #2 and #3

**Comment by mhallin** [comment]
Thanks a lot for these fixes! I'll merge this and get things ready for a new opam release.

**Pull request merged**
