### PR TITLE
Parsed & marshaled lazily + configurable path

### PR DESCRIPTION
**Pull request by Huxpro**
This PR adds:

1. Configurable schema path via PPX arguments. See [bsconfig.json L4](https://github.com/mhallin/graphql_ppx/compare/master...Huxpro:master#diff-5589b32fd3a4758926d033abe687466bR4)
2. Lazily parse JSON schema on first use. See [graphql_ppx.ml L108](https://github.com/mhallin/graphql_ppx/compare/master...Huxpro:master#diff-a67e14f78beea1093ad499502071b2beR108)
3. Marshaled the parsed schema for perf (memoizing the parsed result). 

The combination of 2 and 3 see 100x perf wins internally at FB.

### CODE REVIEW

**Comment by mhallin** [comment]
Wow, thanks!

For the memoization, I suggest the following changes:

* Use `.cache` as a suffix instead; it better conveys the meaning for people who don't know what "marshalled" means :) You also might consider adding a `.` prefix to make it hidden.
* Rebuild the cache file if the JSON file is newer than the cache file.
* Fall back to rebuilding the cache if an exception is raised by `Marshal.from_channel`.

**Comment by Huxpro** [comment]
The amended commit adds:

1. A `Dirty_checker` module. One reason to write is as a dedicated module is that we at FB uses it in other places. (Not sure should I abstract out as an OPAM dependency. I heard that the process is quite tedious.). 
2. Naming. Now it's named as `.<schema_file>.cache` and `.<schema_file>.hash`. I was trying to gather them in a single `.graphql_ppx` dir but not sure if `Unix.mkdir` works in windows. (I wish someone under windows can help us testing `Unix.mkdir` and `Unix.stat`)
3. Recovery builds when `from_channel` throwing exceptions. Not sure if the current implementation is good enough since it assumes the re-reading after rebuilding would not throw.

**Comment by mhallin** [comment]
Despite being named `Unix`, quite a lot of that module works on Windows too :) Here's a list of issues: http://caml.inria.fr/pub/docs/manual-ocaml-4.02/libunix.html. According to this, `mkdir` and `stat` should be fine.

For AppVeyor, try either omitting the `-path` argument completely, or wrap the string inside another string, like `"ppx-flags": ["'../graphql_ppx.exe\\ -path=graphql_schema.json'"]`. The problem comes from backslash not being an escape character on Windows, and that the entire string should be passed as one command to bsb. I _guess_ this could be considered a bug in the Bucklescript compiler.

**Comment by Huxpro** [comment]
The amended commit includes:

- putting artifacts under `.graphql_ppx_cache`, change naming convention to be more developer friendly since for end users they only need to know `.graphql_ppx_cache` now.
- `Unix.stat` are not used for dirty checking since `Digest` is faster enough for now and possibly more robust. (Dirty_checker is flexible enough to provide 2nd mechanism tho)
- changing `path` to `schema`
- add module `Log` and `-verbose` arg
- documentation in README
- remove args in `bsconfig.json` for windows CI.
- improve recovery build

**Pull request merged**
