### PR TITLE
Add instructions re. use of aliases for non-camelCase GraphQL Fields

### PR DESCRIPTION
**Pull request by Phylodome**
Per commentary here, add some context on how to deal w/ capitalized fields:
https://github.com/mhallin/graphql_ppx/issues/9#issuecomment-476906443

### CODE REVIEW

**Review by baransu — COMMENTED** [review]
Great 🚀

One small thing. I think comment inside GraphQL snippet should be GraphQL comment instead of Reason comment ;)

**Review by baransu — APPROVED** [review]

**Comment by baransu** [comment]
@mhallin Could you merge this?

**Comment by baransu** [comment]
@Phylodome Would be amazing if you could submit PR to https://github.com/baransu/graphql_ppx_re or allow me to copy it into the documentation. 😃

**Comment by Phylodome** [comment]
@baransu You are more than welcome to copy it over. Seems like the simplest path.

What are your plans for `graphql_ppx_re`?

**Comment by baransu** [comment]
@Phylodome A lot is happening right now, we try to figure out graphql_ppx future story. Stay tuned

**Comment by Phylodome** [comment]
To what channel should I tune?

**Pull request closed without merging**
